// resources/js/components/Modal.vue
<script setup lang="ts">
import { computed, type Component } from 'vue';
import * as LucideIcons from 'lucide-vue-next';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';

const props = defineProps<{
    open: boolean;
    title?: string;
    description?: string;
    closeOnBackdrop?: boolean;
    icon?: string;
    iconColor?: string;
}>();

const emit = defineEmits<{
    'update:open': [value: boolean];
    'close': [];
}>();

const isOpen = computed({
    get: () => props.open,
    set: (value) => {
        emit('update:open', value);
        if (!value) {
            emit('close');
        }
    },
});

// Keep the dialog open on outside clicks when closeOnBackdrop is explicitly false (Escape and the close button still work)
const onInteractOutside = (event: Event) => {
    if (props.closeOnBackdrop === false) {
        event.preventDefault();
    }
};

// Get Lucide icon component from icon name
const iconComponent = computed<Component | null>(() => {
    if (!props.icon) return null;

    // If it starts with 'heroicon-o-', map it to Lucide
    if (props.icon.startsWith('heroicon-o-')) {
        const iconMap: Record<string, string> = {
            'heroicon-o-bolt': 'Zap',
            'heroicon-o-star': 'Star',
            'heroicon-o-exclamation-triangle': 'AlertTriangle',
            'heroicon-o-document-text': 'FileText',
            'heroicon-o-trash': 'Trash2',
            'heroicon-o-information-circle': 'Info',
            'heroicon-o-squares-2x2': 'LayoutGrid',
            'heroicon-o-x-mark': 'X',
            'heroicon-o-beaker': 'Flask',
            'heroicon-o-home': 'Home',
            'heroicon-o-user': 'User',
            'heroicon-o-users': 'Users',
            'heroicon-o-cog': 'Settings',
            'heroicon-o-chart-bar': 'BarChart',
            'heroicon-o-folder': 'Folder',
            'heroicon-o-shopping-cart': 'ShoppingCart',
        };

        const lucideName = iconMap[props.icon] || 'Circle';
        return (LucideIcons as any)[lucideName] || LucideIcons.Circle;
    }

    // Try to use it as a Lucide icon name directly
    return (LucideIcons as any)[props.icon] || LucideIcons.Circle;
});

// Get icon color classes
const iconColorClasses = computed(() => {
    const colorMap: Record<string, string> = {
        'danger': 'text-red-500',
        'warning': 'text-yellow-500',
        'success': 'text-green-500',
        'info': 'text-blue-500',
        'primary': 'text-primary',
    };

    return props.iconColor ? colorMap[props.iconColor] || 'text-muted-foreground' : 'text-muted-foreground';
});
</script>

<template>
    <Dialog v-model:open="isOpen">
        <DialogContent @interact-outside="onInteractOutside">
            <DialogHeader v-if="title || description || iconComponent">
                <div v-if="iconComponent" class="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-muted mb-4">
                    <component :is="iconComponent" :class="['h-6 w-6', iconColorClasses]" />
                </div>
                <DialogTitle v-if="title">{{ title }}</DialogTitle>
                <DialogDescription v-if="description">{{ description }}</DialogDescription>
            </DialogHeader>

            <slot />

            <DialogFooter v-if="$slots.footer">
                <slot name="footer" />
            </DialogFooter>
        </DialogContent>
    </Dialog>
</template>

// resources/react/components/Modal.tsx
import * as LucideIcons from 'lucide-react';
import type { ComponentType, ReactNode } from 'react';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import { cn } from '@/lib/utils';

export interface ModalProps {
    open: boolean;
    title?: string;
    description?: string;
    closeOnBackdrop?: boolean;
    icon?: string;
    iconColor?: string;
    /** Vue `update:open` event. */
    onUpdateOpen?: (value: boolean) => void;
    /** Vue `close` event — fired whenever the dialog is closed. */
    onClose?: () => void;
    children?: ReactNode;
    /** Vue named slot `footer`. */
    footer?: ReactNode;
}

const heroiconMap: Record<string, string> = {
    'heroicon-o-bolt': 'Zap',
    'heroicon-o-star': 'Star',
    'heroicon-o-exclamation-triangle': 'AlertTriangle',
    'heroicon-o-document-text': 'FileText',
    'heroicon-o-trash': 'Trash2',
    'heroicon-o-information-circle': 'Info',
    'heroicon-o-squares-2x2': 'LayoutGrid',
    'heroicon-o-x-mark': 'X',
    'heroicon-o-beaker': 'Flask',
    'heroicon-o-home': 'Home',
    'heroicon-o-user': 'User',
    'heroicon-o-users': 'Users',
    'heroicon-o-cog': 'Settings',
    'heroicon-o-chart-bar': 'BarChart',
    'heroicon-o-folder': 'Folder',
    'heroicon-o-shopping-cart': 'ShoppingCart',
};

const iconColorMap: Record<string, string> = {
    danger: 'text-red-500',
    warning: 'text-yellow-500',
    success: 'text-green-500',
    info: 'text-blue-500',
    primary: 'text-primary',
};

/**
 * Same lookup as the Vue component: exact lucide export name (heroicon-o-* mapped first), falling back to Circle.
 */
function getIconComponent(icon?: string): ComponentType<{ className?: string }> | null {
    if (!icon) {
        return null;
    }

    const all = LucideIcons as unknown as Record<string, ComponentType<{ className?: string }>>;

    if (icon.startsWith('heroicon-o-')) {
        const lucideName = heroiconMap[icon] || 'Circle';

        return all[lucideName] || LucideIcons.Circle;
    }

    return all[icon] || LucideIcons.Circle;
}

export default function Modal({
    open,
    title,
    description,
    closeOnBackdrop,
    icon,
    iconColor,
    onUpdateOpen,
    onClose,
    children,
    footer,
}: ModalProps) {
    const IconComponent = getIconComponent(icon);

    const iconColorClasses = iconColor ? iconColorMap[iconColor] || 'text-muted-foreground' : 'text-muted-foreground';

    const handleOpenChange = (value: boolean) => {
        onUpdateOpen?.(value);

        if (!value) {
            onClose?.();
        }
    };

    return (
        <Dialog open={open} onOpenChange={handleOpenChange}>
            <DialogContent
                // Keep the dialog open on outside clicks when closeOnBackdrop is explicitly false (Escape and the close button still work)
                onInteractOutside={(event) => {
                    if (closeOnBackdrop === false) {
                        event.preventDefault();
                    }
                }}
            >
                {(title || description || IconComponent) && (
                    <DialogHeader>
                        {IconComponent && (
                            <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-muted mb-4">
                                <IconComponent className={cn('h-6 w-6', iconColorClasses)} />
                            </div>
                        )}
                        {title && <DialogTitle>{title}</DialogTitle>}
                        {description && <DialogDescription>{description}</DialogDescription>}
                    </DialogHeader>
                )}

                {children}

                {footer != null && <DialogFooter>{footer}</DialogFooter>}
            </DialogContent>
        </Dialog>
    );
}

export { Modal };
