// resources/react/components/ComponentRenderer.tsx
export interface ComponentRendererProps {
    componentName: string;
    /** Accepted for API parity; the Vue component does not use it either. */
    componentProps?: Record<string, any>;
    componentKey: string;
    innerHTML?: string;
}

export default function ComponentRenderer({ componentName, componentKey, innerHTML = '' }: ComponentRendererProps) {
    return (
        <div
            data-laravilt-component={componentName}
            data-laravilt-key={componentKey}
            dangerouslySetInnerHTML={{ __html: innerHTML }}
        />
    );
}

export { ComponentRenderer };

// resources/js/components/ComponentRenderer.vue
<template>
    <div
        :data-laravilt-component="componentName"
        :data-laravilt-key="componentKey"
        v-html="innerHTML"
    />
</template>

<script setup>
const props = defineProps({
    componentName: {
        type: String,
        required: true
    },
    componentProps: {
        type: Object,
        default: () => ({})
    },
    componentKey: {
        type: String,
        required: true
    },
    innerHTML: {
        type: String,
        default: ''
    }
});
</script>
